trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  displayName: 'Terraform version'
  inputs:
    terraformVersion: '0.15.2'
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    addSpnToEnvironment: true
    azureSubscription: ServConnectionName
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show
 
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    commandOptions: '-backend-config=backend.tfconfig'
    backendServiceArm: 'ServConnectionName'
    backendAzureRmResourceGroupName: 'diego-gomez'
    backendAzureRmStorageAccountName: 'team3demodou'
    backendAzureRmContainerName: 'tstate'
    backendAzureRmKey: '$(System.DefaultWorkingDirectory)/infra/.terraform/terraform.tfstate'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    environmentServiceNameAzureRM: 'ServConnectionName'

# - task: TerraformTaskV2@2
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
#     commandOptions: '-auto-approve'
#     environmentServiceNameAzureRM: 'ServConnectionName'